apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-chatapp
  labels:
    role: chatapp
spec:
  replicas: 3
  selector:
    matchLabels:
      role: chatapp
  template:
    metadata:
      name: frontend-pod
      labels:
        role: chatapp
    spec:
      containers:
      - name: frontend-chatapp
        image: atharvak2427/frontend-chatapp
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    role: chatapp
  type: NodePort
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30010 